data:
  cat: car
  train:
    origin: shapenet
    path: #### path to data
    split: full
    bg: True
    bg_path: #### path to data
  val:
    origin: pascal
    subset: imagenet
    split: train
    path: #### path to data
  test:
    origin: pascal
    subset: imagenet
    split: val
    path: #### path to data

training:
  cuda: True
  cycle: False
  bs: 64
  epochs: 1000
  lr: 0.0001
  eps: 9
  resume: 0
  resume_path: 
  ckpt_path: #### path to checkpoints

model:
  cont_size: 256
  n_heads: 3